#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $DIR/config

if ! [ -f "$QUERY" ];
then
  echo "SPARQL Query file not found."
  exit 0
fi
echo

REQUESTS=$(($REQUESTS - 1))
COUNT=0

echo ""
input="data/uris.txt"
while read -r line
do
  echo "$line"
  curl -s --digest --user "$MLUSER:$MLPASS" -X POST \
    --data-binary @$QUERY \
    -H "Content-type: application/sparql-query" \
    -H "Accept: application/sparql-results+xml" \
    http://localhost:8000/v1/graphs/sparql?bind:resource_uri=$line
  echo ""
  COUNT=$(($COUNT + 1))
  if [ "$COUNT" -gt "$REQUESTS" ]
  then
    break
  fi
done < "$input"